-- Buat tabel kumpulan_dokumen
CREATE TABLE IF NOT EXISTS public.kumpulan_dokumen (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama text NOT NULL,
    kode_jenis text NOT NULL UNIQUE,
    created_at timestamp with time zone DEFAULT now()
);

-- Tambahkan kolom dokumen_kode_jenis ke jenis_pengumuman jika belum ada
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'jenis_pengumuman'
          AND column_name = 'dokumen_kode_jenis'
    ) THEN
        ALTER TABLE public.jenis_pengumuman ADD COLUMN dokumen_kode_jenis text;
    END IF;
END $$;
